# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       harbour-sailgrande

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    An unofficial client for Instagram
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
Version:    0.5.0
=======
Version:    0.5.2
>>>>>>> a55a368... version bump to 0.5.2
=======
Version:    0.5.2
>>>>>>> a55a368... version bump to 0.5.2
=======
Version:    0.5.2
>>>>>>> a55a368... version bump to 0.5.2
Release:    1
Group:      Qt/Qt
License:    MIT License
URL:        https://openrepos.net/content/forgrimm/sailgrande
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-sailgrande.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils

%description
SailGrande is an unofficial client for Instagram


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/86x86/apps/%{name}.png
# >> files
# << files
